// Auto-generated by Client\embed-driver.ps1 -- do not edit.
#pragma once
#include <cstddef>
namespace LongsDriverBlobKey {
static const std::size_t size = 42496;
static const std::size_t compressed_size = 18791;
static const unsigned char key[16] = {
0x48,0xB4,0x2E,0xB1,0xF4,0xB7,0x58,0x4D,0xE2,0x95,0xCE,0x36,0x06,0x5C,0xAC,0x79,
};
} // namespace LongsDriverBlobKey
