// Auto-generated by Client\embed-driver.ps1 -- do not edit.
#pragma once
#include <cstddef>
namespace LongsDriverBlobKey {
static const std::size_t size = 55296;
static const std::size_t compressed_size = 25030;
static const unsigned char key[16] = {
0xB4,0xCD,0x39,0x59,0x78,0x7A,0x05,0xBB,0x22,0x80,0xA4,0x2F,0x0A,0x8E,0x8B,0x67,
};
} // namespace LongsDriverBlobKey
