// Auto-generated by Client\embed-driver.ps1 -- do not edit.
#pragma once
#include <cstddef>
namespace LongsDriverBlobKey {
static const std::size_t size = 54272;
static const std::size_t compressed_size = 24672;
static const unsigned char key[16] = {
0xE8,0xF6,0x16,0xE5,0x6C,0x07,0x33,0x39,0x3B,0xA1,0xCC,0x10,0x5F,0xB4,0x44,0x50,
};
} // namespace LongsDriverBlobKey
